name: circle
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  supabase_flutter: ^2.10.1
  google_sign_in: ^7.2.0
  image_picker: ^1.0.7
  image_cropper: ^11.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4 # Added package

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/logo.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
    - family: Katahdin Round
      fonts:
        - asset: assets/fonts/KatahdinRound.otf

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#205692" # Optional: if you want a specific background for Android adaptive icons
  # adaptive_icon_foreground: "assets/images/logo_foreground.png" # Optional: if you want a different foreground for Android adaptive icons
